layout: sidebar
style: light
repository: crock/personal-website

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - stars
    - push
  limit: 9
  exclude:
    forks: true
    projects:
    - dotfiles
    - personal-website
    - cma
    - yoix
    - "404"
    - ogcheckr-web
    - croc-navigation
    - snap-src
    - dcbot
    - donate-bot
    - crock.github.io
    - jekyll-site
    - portfolio
    - penguin-issues
    - discord-bot
    - myLoop-client
    - php-micro-framework
    - steamcheck
    - chivalry-portal
    - sarahah-bot
    - cbs-portal

social_media:
  # behance: alexcrocker
  dribbble: croc
  # facebook: your_username
  linkedin: awcrocker
  medium: "@alexcrocker"
  # stackoverflow: croc122
  # telegram: crocbuzz
  twitter: acrockr
  # youtube: alexcrocker
  # vk: your_username

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
